// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("MemoryFragmentToMemoryUsingMemory", testMemoryFragmentToOneMemoryUsingMemory)
	t.Run("MessageToConversationUsingConversation", testMessageToOneConversationUsingConversation)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("ConversationToMessages", testConversationToManyMessages)
	t.Run("MemoryToMemoryFragments", testMemoryToManyMemoryFragments)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("MemoryFragmentToMemoryUsingMemoryFragments", testMemoryFragmentToOneSetOpMemoryUsingMemory)
	t.Run("MessageToConversationUsingMessages", testMessageToOneSetOpConversationUsingConversation)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("MemoryFragmentToMemoryUsingMemoryFragments", testMemoryFragmentToOneRemoveOpMemoryUsingMemory)
	t.Run("MessageToConversationUsingMessages", testMessageToOneRemoveOpConversationUsingConversation)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("ConversationToMessages", testConversationToManyAddOpMessages)
	t.Run("MemoryToMemoryFragments", testMemoryToManyAddOpMemoryFragments)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("ConversationToMessages", testConversationToManySetOpMessages)
	t.Run("MemoryToMemoryFragments", testMemoryToManySetOpMemoryFragments)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("ConversationToMessages", testConversationToManyRemoveOpMessages)
	t.Run("MemoryToMemoryFragments", testMemoryToManyRemoveOpMemoryFragments)
}
