// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Cache           string
	Conversations   string
	GooseDBVersion  string
	Memories        string
	MemoryFragments string
	Messages        string
}{
	Cache:           "cache",
	Conversations:   "conversations",
	GooseDBVersion:  "goose_db_version",
	Memories:        "memories",
	MemoryFragments: "memory_fragments",
	Messages:        "messages",
}
